[package]
name = "sgx-prover"
version = "1.0.0"
license = "Apache-2.0"
edition = "2021"

[package.metadata.geode]
enclaves = [
    "./enclave",
]

[build-dependencies]
ata-sgx-builder = { git = "https://github.com/automata-network/sgxlib" }

[dependencies]
glog = { git = "https://github.com/automata-network/glog-rs" }
hex = { git = "https://github.com/automata-network/hex-rs" }
app = { git = "https://github.com/automata-network/app-rs" }
sgxlib-enclave = { git = "https://github.com/automata-network/sgxlib" }
sgxlib-ra = { git = "https://github.com/automata-network/sgxlib-ra", default-features = false, features = ["std", "dcap_std"] }

serde_json = { git = "https://github.com/automata-network/sgxlib-thirdparty" }