[package]
name = "std-prover"
version = "1.0.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]
glog = { git = "https://github.com/automata-network/glog-rs" }
app = { git = "https://github.com/automata-network/app-rs" }
app-prover = { path = "../../../src/apps/prover" }
